#
###################################
# Site wide configuration
####################################
#
title: JMPortfolio
email:
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Rome
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jacopo Maiolini
  avatar: leonids-logo.png
  job: "Robotic Software Engineer"
  bio: "A simple and awesome blog theme powered by jekyll.A simple and awesome blog theme powered by jekyll.A simple and awesome blog theme powered by jekyll.A simple and awesome blog theme powered by jekyll.A simple and awesome blog theme powered by jekyll.A simple and awesome blog theme powered by jekyll."
  email: jacopo.maiolini@gmail.com
  disqus-shortname:
  twitter: 
  facebook: 
  google:
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jmaiolini
  bitbucket: jmaiolini
  gitlab: 
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jacopo-maiolini
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

#keep old pages but exclude them from being served
exclude: [old_pages, old_posts]
